frequencia/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.urls import path

from frequencia.accounts import views

app_name = 'accounts'
urlpatterns = [
	path('entrar/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
	path('sair/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_URL), name='logout'),
	
	path('usuarios/', views.accounts, name='accounts'),
	path('usuario/novo/', views.accounts_create, name='accounts_create'),
	path('usuario/editar/<int:pk>/', views.accounts_edit, name='accounts_edit'),
	path('usuario/editar_senha/', views.edit_password, name='edit_password'),
	path('usuario/redefinir_senha/<int:pk>/', views.reset_password, name='reset_password'),
]

frequencia/core/urls.py
from django.urls import path

from frequencia.core import views

app_name = 'core'
urlpatterns = [
	path('', views.index, name='index'),
	path('home/', views.home, name='home'),
	path('nova-mensagem/', views.nova_mensagem, name='nova_mensagem'),
]

frequencia/registro/urls.py
from django.urls import path

from frequencia.registro import views

app_name = 'registro'
urlpatterns = [
	#Máquinas
	path('maquinas/', views.maquinas, name='maquinas'),
	path('maquina/novo/', views.maquina_create, name='maquina_create'),
	path('maquina/editar/<int:pk>/', views.maquina_edit, name='maquina_edit'),
	path('maquina/remover/<int:pk>/', views.maquina_remove, name='maquina_remove'),

	#Registro
	path('', views.registro, name='registro'),
	path('registros_dia/', views.registros_dia, {'Bolsista': None}, name='registros_dia'),
    path('api/', views.registro_api, name='registro_api')
]

frequencia/urls.py
from django.urls import path
from django.conf import settings
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('frequencia.core.urls', namespace='core')),
    path('registro/', include('frequencia.registro.urls', namespace='registro')),
    path('vinculos', include('frequencia.vinculos.urls', namespace='vinculos')),
    path('calendario/', include('frequencia.calendario.urls', namespace='calendario')),
    path('justificativas/', include('frequencia.justificativas.urls', namespace='justificativas')),
    path('relatorios/', include('frequencia.relatorios.urls', namespace='relatorios')),
    path('conta/', include('frequencia.accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

# urlpatterns = [
#     url(r'^', include('frequencia.core.urls', namespace='core')),
#     url(r'^registro/', include('frequencia.registro.urls', namespace='registro')),
#     url(r'^vinculos/', include('frequencia.vinculos.urls', namespace='vinculos')),
#     url(r'^calendario/', include('frequencia.calendario.urls', namespace='calendario')),
# 	url(r'^justificativas/', include('frequencia.justificativas.urls', namespace='justificativas')),
# 	url(r'^relatorios/', include('frequencia.relatorios.urls', namespace='relatorios')),

#     url(r'^admin/', admin.site.urls),
#     url(r'^conta/', include('frequencia.accounts.urls', namespace='accounts')),
# ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frequencia/accounts/models.py
import re

from django.db import models
from django.db.models import Q
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.conf import settings

from frequencia.core.basemodel import basemodel

class CustomUserManager(UserManager):
	def buscar(self, query):
		return self.filter(Q(name__icontains=query) | Q(username__icontains=query) | Q(cpf__icontains=query))

class User(basemodel, AbstractBaseUser, PermissionsMixin):

	username = models.CharField(
		'Login', max_length=30, unique=True,
		validators=[validators.RegexValidator(re.compile('^[\w.@+-]+$'),
			'O nome de usuário so pode conter letras, digitos ou os seguintes caracteres: @/./+/-/_', 'invalid')]
	)
	email = models.EmailField('E-mail', blank=True)
	name = models.CharField('Nome', max_length=100, blank=True)
	cpf = models.CharField('CPF', max_length=15, unique=True)
	is_active = models.BooleanField('Está ativo', blank=True, default=True)
	is_staff = models.BooleanField('Acesso ao admin do projeto', blank=True, default=False)

	objects = CustomUserManager()

	USERNAME_FIELD = 'username'
	REQUIRED_FIELDS = ['email']

	def __str__(self):
		return self.name or self.username

	def get_short_name(self):
		return self.username

	def get_full_name(self):
		return str(self)

	class Meta:
		verbose_name='Usuário'
		verbose_name_plural='Usuários'

frequencia/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group

from frequencia.vinculos.models import Setor

User = get_user_model()

class RegisterForm(forms.ModelForm):

	password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
	password2 = forms.CharField(
		label='Confirmação de Senha', widget=forms.PasswordInput
	)

	def clean_password2(self):
		password1 = self.cleaned_data.get("password1")
		password2 = self.cleaned_data.get("password2")
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError("Confirmação de senha incorreta")
		return password2

	def save(self, commit=True):
		user = super(RegisterForm, self).save(commit=False)
		user.set_password(self.cleaned_data['password1'])

		if commit:
			user.save()
		return user

	class Meta:
		model = User
		fields = ['name', 'username', 'email', 'cpf', 'is_active']


class EditAccountForm(forms.ModelForm):

	class Meta:
		model = User
		fields = ['username','email','name', 'cpf', 'is_active']

frequencia/accounts/views.py
from rules.contrib.views import PermissionRequiredMixin, permission_required

from django.urls import reverse
from django.contrib import messages
from django.views.generic import ListView
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect
from django.views.generic.base import RedirectView
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView, CreateView
from django.contrib.messages.views import SuccessMessageMixin
from django.forms import formset_factory, inlineformset_factory
from django.shortcuts import render, redirect, get_object_or_404

from frequencia.vinculos.forms import AdicionarVinculoForm, EditarVinculoForm
from frequencia.vinculos.models import Vinculo

from .models import User
from .forms import RegisterForm, EditAccountForm


class AccountListView(PermissionRequiredMixin, ListView):
	model = User
	template_name = 'accounts/accounts.html'
	permission_required = 'accounts.is_gestor'

	def get_queryset(self):
		busca = self.request.GET.get('busca', '')
		return User.objects.buscar(busca) if busca else User.objects.filter(is_active=True)

	def get_context_data(self, **kwargs):
		context = super(AccountListView, self).get_context_data(**kwargs)
		queryset = context['object_list']
		context['busca'] = True if self.request.GET.get('busca') else False
		context['bolsistas'] = queryset.filter(vinculos__ativo=True, vinculos__group__name='Bolsista')
		context['chefes'] = queryset.filter(vinculos__ativo=True, vinculos__group__name='Chefe de setor')
		context['coordenadores'] = queryset.filter(vinculos__ativo=True, vinculos__group__name='Coordenador')
		context['gestores'] = queryset.filter(vinculos__ativo=True, vinculos__group__name='Gestor de unidade')
		return context

@permission_required('accounts.is_gestor')
def accounts_create(request):
	template_name = 'accounts/accounts_create_edit.html'

	VinculosFormset = formset_factory(AdicionarVinculoForm)
	
	form = RegisterForm(request.POST or None)

	vinculos_form = VinculosFormset(request.POST or None, prefix='vinculos')	

	if form.is_valid() and vinculos_form.is_valid():
		user = form.save()
		for vinculo_form in vinculos_form:			
			vinculo_form.save(user)
		messages.info(request, 'Usuário cadastrado com sucesso!')
		return redirect('accounts:accounts')
	
	context = {
		'form': form,
		'vinculos_formset': vinculos_form,
	}
	return render(request, template_name, context)

@permission_required('accounts.is_gestor')
def accounts_edit(request, pk): 
	template_name = 'accounts/accounts_create_edit.html'

	instance = get_object_or_404(User, pk=pk)
	form = EditAccountForm(request.POST or None, instance=instance)

	VinculosFormset = inlineformset_factory(User, Vinculo, exclude=('user',), extra=1, can_delete=False, form=EditarVinculoForm)
	vinculos_formset = VinculosFormset(request.POST or None, instance=instance, prefix='vinculos')

	if form.is_valid() and vinculos_formset.is_valid():
		form.save()
		vinculos_formset.save()
		messages.info(request, 'Usuário atualizado com sucesso!')
		return redirect(reverse('accounts:accounts_edit', kwargs={'pk':pk}))
	context = {
		'form': form,
		'vinculos_formset': vinculos_formset,
		'object' : instance,
	}
	return render(request, template_name, context)

@login_required
def edit_password(request):
	template_name = 'accounts/edit_password.html'
	context = {}
	
	form = PasswordChangeForm(data=request.POST or None, user=request.user)
	if form.is_valid():
		form.save()
		messages.info(request, 'Senha alterada com sucesso!')
		#Reautenticando usuário com nova senha		
		update_session_auth_hash(request, form.user)
		return redirect('core:home')
	
	context['form'] = form
	return render(request, template_name, context)

class ResetPasswordRedirectView(PermissionRequiredMixin, RedirectView):

	permission_required = 'accounts.is_gestor'

	permanent = False
	query_string = True

	def get_redirect_url(self, *args, **kwargs):
		user = get_object_or_404(User, pk=kwargs['pk'])
		user.set_password('12345')
		user.save()

		messages.info(self.request, 'Senha do usuário redefinida para <b>12345</b>')
		return reverse('accounts:accounts_edit', kwargs={'pk': user.pk})

accounts = AccountListView.as_view()
reset_password = ResetPasswordRedirectView.as_view()

frequencia/accounts/templates/accounts/accounts.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<div class="card mb-3">
    <div class="card-header">
        <div class="row">
            <div class="col-md-9">
                <i class="fa fa-users"></i> Usuários
            </div>
            <div class="col-md-3">
                <form url="#" method="GET" class="pull-right">
                    <div class="input-group">
                        <input type="text" name="busca" placeholder="Buscar usuário" class="form-control">
                        <span class="input-group-addon"><i class="fa fa-search"></i></span>
                    </div>
                </form>
            </div>
        </div>
    </div>
            
    <div class="card-body">
        {% if not busca %}
            <ul role="tablist" class="nav nav-tabs">
                <li role="presentation">
                    <a data-toggle="tab" href="#bolsistas" class="nav-link active" aria-expanded="true">Bolsistas</a>
                </li>
                <li role="presentation">
                    <a data-toggle="tab" href="#chefes" class="nav-link" aria-expanded="true">Chefes</a>
                </li>
                <li role="presentation">
                    <a data-toggle="tab" href="#coordenadores" class="nav-link" aria-expanded="true">Coordenadores</a>
                </li>
                <li role="presentation">
                    <a data-toggle="tab" href="#gestores" class="nav-link" aria-expanded="true">Gestores</a>
                </li>
            </ul>

            <div class="tab-content table-responsive">
                <div id="bolsistas" class="tab-pane active">
                    <table class="table">
                        <thead>
                            <tr>                          
                                <th>Nome</th>                          
                                <th>Login</th>                          
                                <th>CPF</th>                           
                                <th>E-mail</th>                          
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for account in bolsistas %}
                                <tr>
                                    <td>{{ account.name }}</td>                       
                                    <td>{{ account.username }}</td>
                                    <td>{{ account.cpf }}</td>
                                    <td>{{ account.email }}</td>
                                    <td><a href="{% url 'accounts:accounts_edit' account.pk %}"><i class="fas fa-pencil-alt pull-right"></i></a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div id="chefes" class="tab-pane">
                    <table class="table">
                        <thead>
                            <tr>                          
                                <th>Nome</th>                          
                                <th>Login</th>                          
                                <th>CPF</th>                           
                                <th>E-mail</th>                          
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for account in chefes %}
                                <tr>
                                    <td>{{ account.name }}</td>                       
                                    <td>{{ account.username }}</td>
                                    <td>{{ account.cpf }}</td>
                                    <td>{{ account.email }}</td>
                                    <td><a href="{% url 'accounts:accounts_edit' account.pk %}"><i class="fas fa-pencil-alt pull-right"></i></a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div id="coordenadores" class="tab-pane">
                    <table class="table">
                        <thead>
                            <tr>                          
                                <th>Nome</th>                          
                                <th>Login</th>                          
                                <th>CPF</th>                           
                                <th>E-mail</th>                          
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for account in coordenadores %}
                                <tr>
                                    <td>{{ account.name }}</td>                       
                                    <td>{{ account.username }}</td>
                                    <td>{{ account.cpf }}</td>                                            
                                    <td>{{ account.email }}</td>
                                    <td><a href="{% url 'accounts:accounts_edit' account.pk %}"><i class="fas fa-pencil-alt pull-right"></i></a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div id="gestores" class="tab-pane">                        
                    <table class="table">
                        <thead>
                            <tr>                          
                                <th>Nome</th>                          
                                <th>Login</th>                          
                                <th>CPF</th>                             
                                <th>E-mail</th>                          
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for account in gestores %}
                                <tr>
                                    <td>{{ account.name }}</td>                       
                                    <td>{{ account.username }}</td>
                                    <td>{{ account.cpf }}</td>                                            
                                    <td>{{ account.email }}</td>
                                    <td><a href="{% url 'accounts:accounts_edit' account.pk %}"><i class="fas fa-pencil-alt pull-right"></i></a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
           </div>
        {% else %}
            <table class="table">
                <thead>
                    <tr>                          
                        <th>Nome</th>                          
                        <th>Login</th>                          
                        <th>CPF</th>                      
                        <th>Status</th>                          
                        <th>E-mail</th>                          
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for account in object_list %}
                        <tr>
                            <td>{{ account.name }}</td>                       
                            <td>{{ account.username }}</td>
                            <td>{{ account.cpf }}</td>
                            {% if account.is_active %}                    
                            <td>Ativo</td>
                            {% else %}
                            <td>Inativo</td>
                            {% endif %}
                            <td>{{ account.email }}</td>
                            <td><a href="{% url 'accounts:accounts_edit' account.pk %}"><i class="fas fa-pencil-alt pull-right"></i></a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>            
            <div class="text-center">
                <legend></legend>
                <a class="btn text-info" href="{% url 'accounts:accounts' %}">Voltar</a>
            </div>   
       {% endif %}        
            
    </div>
</div>

{% endblock %}

frequencia/accounts/templates/accounts/accounts_create_edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% load widget_tweaks %}

<div class="card mb-3">
	<div class="card-header">
	  <i class="fa fa-user"></i> Gerenciar usuário
	</div>
    <div class="card-body">
        <form method="post">
             {% csrf_token %}              

             {% if form.non_field_errors %}
                <div class="alert alert-danger">
                    {% for error in form.non_field_errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            {% endif %}
            <div class="row">            	
            	<div class="col-md-12">	                
					<label class="checkbox">
                        {% render_field form.is_active %}
                        {{form.is_active.label}}
                    </label>
				</div>
	            <div class="form-group col-md-6">
	            	<label class="control-label">{{form.name.label}}</label>
					{% render_field form.name class="form-control" %}
					{% if form.name.errors %}
	                    <label class="text-danger">{{ form.name.errors.0 }}</label>
	                {% endif %}                        
	            </div>
	            <div class="form-group col-md-6">
	            	<label class="control-label">{{form.username.label}}</label>
					{% render_field form.username class="form-control" %}
					{% if form.username.errors %}
	                    <label class="text-danger">{{ form.username.errors.0 }}</label>
	                {% endif %}                        
	            </div>
	            <div class="form-group col-md-6">
	            	<label class="control-label">{{form.email.label}}</label>
					{% render_field form.email class="form-control" %}
					{% if form.email.errors %}
	                    <label class="text-danger">{{ form.email.errors.0 }}</label>
	                {% endif %}                        
	            </div>
	            <div class="form-group col-md-6">
	            	<label class="control-label">{{form.cpf.label}}</label>
					{% render_field form.cpf class="form-control" %}
					{% if form.cpf.errors %}
	                    <label class="text-danger">{{ form.cpf.errors.0 }}</label>
	                {% endif %}                        
	            </div>
	            <div class="form-group col-md-6">
	            	<label class="control-label">{{form.password1.label}}</label>
					{% render_field form.password1 class="form-control" %}
					{% if form.password1.errors %}
	                    <label class="text-danger">{{ form.password1.errors.0 }}</label>
	                {% endif %}                        
	            </div>
	            <div class="form-group col-md-6">
	            	<label class="control-label">{{form.password2.label}}</label>
					{% render_field form.password2 class="form-control" %}
					{% if form.password2.errors %}
	                    <label class="text-danger">{{ form.password2.errors.0 }}</label>
	                {% endif %}                        
	            </div>
	        </div>

            <h4>Vínculos</h4>

            <ul role="tablist" class="nav nav-tabs">
                {% for form in vinculos_formset %}
                  <li id="{{form.prefix}}-tab"><a data-toggle="tab" class="nav-link{% if form.prefix == 'vinculos-0' %} active {% endif %}" href="#{{form.prefix}}">Novo vínculo</a></li>
                {% endfor %}
            </ul>
            {{vinculos_formset.management_form}}
            <div id="tab-content" class="tab-content">
				{% for form in vinculos_formset %}					
                  	<div id="{{form.prefix}}" class="tab-pane {% if form.prefix == 'vinculos-0' %} active{% endif %}">		  
						<div class="row">
						{% for field in form %}							
							{% if field.name == "ativo" %}
								<div class="col-md-12">
									<label class="checkbox">
										{% render_field field %}
										{{field.label}}
			                        </label>
								</div>
							{% elif field.name == "id" or field.name == "user" %}
								{% render_field field %}
								{% if field.errors %}
				                    <label class="text-danger">{{ field.errors.0 }}</label>
				                {% endif %}
							{% elif field.name == "group" %}
         						<div class="col-md-6">
									<div class="form-group">
										<label class="control-label">{{field.label}}</label>
										{% render_field field class="form-control" onchange="getOption(this)" %}
									</div>
								</div>
							{% else %}
         						<div class="col-md-6">
									<div class="form-group">
										<label class="control-label">{{field.label}}</label>
										{% render_field field class="form-control" %}
										{% if field.errors %}
						                    <label class="text-danger">{{ field.errors.0 }}</label>
						                {% endif %}
									</div>
								</div>
							{% endif %}
					    {% endfor %}                    	
						</div>
                  	</div>
				{% endfor %}
            </div>

             						
            <div class="text-center">
		    	<a class="btn text-info" href="{% url 'accounts:accounts' %}">Voltar</a>
		    	{% if object %}
		    		<button class="btn btn-danger" data-toggle="modal" data-target="#confirmar_redefinicao" type="button">Redefinir senha</button>
		    	{% endif %}
			    <button class="btn btn-info" type="submit">Salvar</button>
			</div>            
        </form>
    </div>
</div> 

{% if object %}
	<div class="modal fade" id="confirmar_redefinicao" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
	        <h4 class="modal-title" id="myModalLabel">Confirmação de redefinição de senha</h4>
	      </div>
	      <div class="modal-body">
	        Você deseja realmente redefinir a senha do usuário para o valor padrão?
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default btn-simple" data-dismiss="modal">Cancelar</button>
			<a class="btn btn-danger btn-fill" href="{% url 'accounts:reset_password' object.pk %}">Redefinir</a>
	      </div>
	    </div>
	  </div>
	</div>
{% endif %}


{% endblock %}

{% block extra-scripts %}
	<script src="{% static 'js/jquery.mask.js' %}"></script>
	<script type="text/javascript">
	    $(document).ready(function(){
		    $("div ul li a").val('name');

		    var $seuCampoCpf = $("#id_cpf");
	        $seuCampoCpf.mask('000.000.000-00', {reverse: true});

	        $('[id*=-group]').each(function() {
				getOption($(this));
			});

            $('[data-toggle="datepicker"]').datepicker({
                autoHide: true, 
                language: 'pt',
                format: 'dd/mm/yyyy',               
            });
		});

		function getOption(form) {

			var id = $(form).attr("name").split('-')[1];
			var option = $(form).find("option:selected").text()

			if (option == '') {
			    option = "Novo vínculo"
			}

			$("li#vinculos-" + id + "-tab a").text(option);

	    	$('select#id_vinculos-'+id+'-setor').prop('disabled', false);
	    	$('select#id_vinculos-'+id+'-coordenadoria').prop('disabled', false);
	    	$('select#id_vinculos-'+id+'-turno').prop('disabled', false);
	    	$('input#id_vinculos-'+id+'-carga_horaria_diaria').prop('disabled', false);

		    if (option == "Bolsista") {

		        $('select#id_vinculos-'+id+'-coordenadoria').prop('disabled', true).val('');
		        $('input#id_vinculos-'+id+'-inicio_vigencia').prop('disabled', false);
		    	$('input#id_vinculos-'+id+'-termino_vigencia').prop('disabled', false);

		    } else if (option == "Chefe de setor") {

		    	$('select#id_vinculos-'+id+'-coordenadoria').prop('disabled', true).val('');
		    	$('input#id_vinculos-'+id+'-carga_horaria_diaria').prop('disabled', true).val('');
		    	$('select#id_vinculos-'+id+'-turno').prop('disabled', true).val('');
		    	$('select#id_vinculos-'+id+'-turno').prop('disabled', true).val('');
		    	$('input#id_vinculos-'+id+'-inicio_vigencia').prop('disabled', true).val('');
		    	$('input#id_vinculos-'+id+'-termino_vigencia').prop('disabled', true).val('');

		    } else if (option == "Coordenador") {

		    	$('select#id_vinculos-'+id+'-setor').prop('disabled', true).val('');
		    	$('input#id_vinculos-'+id+'-carga_horaria_diaria').prop('disabled', true).val('');
		    	$('select#id_vinculos-'+id+'-turno').prop('disabled', true).val('');
		    	$('input#id_vinculos-'+id+'-inicio_vigencia').prop('disabled', true).val('');
		    	$('input#id_vinculos-'+id+'-termino_vigencia').prop('disabled', true).val('');

		    } else if (option == "Gestor de unidade") {
		    	$('select#id_vinculos-'+id+'-setor').prop('disabled', true).val('');
		    	$('select#id_vinculos-'+id+'-coordenadoria').prop('disabled', true).val('');
		    	$('input#id_vinculos-'+id+'-carga_horaria_diaria').prop('disabled', true).val('');
		    	$('select#id_vinculos-'+id+'-turno').prop('disabled', true).val('');
		    	$('input#id_vinculos-'+id+'-inicio_vigencia').prop('disabled', true).val('');
		    	$('input#id_vinculos-'+id+'-termino_vigencia').prop('disabled', true).val('');
		    };
		};
	</script>
{% endblock %}

frequencia/accounts/templates/accounts/login.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">

{% include "head.html" %}

<style type="text/css">
    body{
        position:relative;
        background: url({% static 'images/bczm-acervo.jpg' %}) no-repeat center center fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
        width:100%;
        height:100%;
        margin:0
    }
    body:after{
        position:fixed;
        content:"";
        top:0;
        left:0;
        right:0;
        bottom:0;
        background:rgba(16, 16, 16, 0.78);
        z-index:-1;
    }  
</style>

<body class="bg-dark fixed-nav sticky-footer "> 
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="{% url 'core:index' %}">
      <img src="{% static 'images/bczm-logo.png' %}" class="logo-nav">
      Frequência BCZM
    </a>
    <ul class="navbar-nav ml-auto">        
        <a class="nav-link" href="{% url 'registro:registro' %}"><i class="far fa-clock"></i> Registrar frequência</a>
    </ul>
  </nav>

  <div class="container">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header">Entrar</div>
      <div class="card-body">
         <form action="{% url 'accounts:login' %}" method="POST">
          {% csrf_token %}

          <input type="hidden" name="next" value="{{ next }}">   
          {% if form.errors %}
              <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>                
                <span>{{ form.non_field_errors.0 }}</span>
              </div>
          {% endif %}
          <div class="form-group">
              <label>{{ form.username.label }}</label>
              {% render_field form.username class="form-control" autofocus="" %}
              {% if form.username.errors %}
                  <label class="error">{{ form.username.errors.0 }}</label>
              {% endif %} 
          </div>
          <div class="form-group">
              <label>{{ form.password.label }}</label>
               {% render_field form.password class="form-control" %}
               {% if form.password.errors %}
                  <label class="error">{{ form.password.errors.0 }}</label>
               {% endif %} 
          </div> 
          <hr>
          <button class="btn btn-primary btn-block" href="index.html" type="submit">Login</button>
        </form>        
      </div>
    </div>    
  </div>

<div class="container-fluid footer navbar-fixed-bottom text-center" id="footer-wrapper">
    <small style="color: #FFF"> © Biblioteca Central Zila Mamede - {% now "Y" %}</small>
</div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/popper/popper.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <script type="text/javascript">
      if ($(document.body).height() < $(window).height()) {
          $('#footer-wrapper').attr('style', 'position: fixed!important; bottom: 20px;');
        }
  </script>
</body>

</html>