frequencia/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.urls import path

from frequencia.accounts import views

app_name = 'accounts'
urlpatterns = [
	path('entrar/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
	path('sair/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_URL), name='logout'),
	
	path('usuarios/', views.accounts, name='accounts'),
	path('usuario/novo/', views.accounts_create, name='accounts_create'),
	path('usuario/editar/<int:pk>/', views.accounts_edit, name='accounts_edit'),
	path('usuario/editar_senha/', views.edit_password, name='edit_password'),
	path('usuario/redefinir_senha/<int:pk>/', views.reset_password, name='reset_password'),
]

frequencia/calendario/urls.py
from django.urls import path

from frequencia.calendario import views

app_name = 'calendario'
urlpatterns = [
	#Feriados
	path('', views.feriados, name='feriados'),
	path('<int:ano>', views.feriados, name='feriados'),
	path('feriado/novo/', views.feriado_create, name='feriado_create'),
	path('feriado/remover/<int:pk>', views.feriado_remove, name='feriado_remove'),
]

frequencia/core/urls.py
from django.urls import path

from frequencia.core import views

app_name = 'core'
urlpatterns = [
	path('', views.index, name='index'),
	path('home/', views.home, name='home'),
	path('nova-mensagem/', views.nova_mensagem, name='nova_mensagem'),
]

frequencia/justificativas/urls.py
from django.urls import path

from frequencia.justificativas import views

app_name = 'justificativas'
urlpatterns = [
	#Tipos de justificativa
	path('tipos/', views.tipo_justificativa, name='tipo_justificativa'),
	path('tipo/novo/', views.tipo_justificativa_create, name='tipo_justificativa_create'),
	path('tipo/editar/<int:pk>/', views.tipo_justificativa_edit, name='tipo_justificativa_edit'),
	path('tipo/remover/<int:pk>/', views.tipo_justificativa_remove, name='tipo_justificativa_remove'),

	#Justificativa de falta
	path('', views.justificativas, name='justificativas'),	
	path('novo/', views.justificativa_create, name='justificativa_create'),
	path('detalhes/<int:pk>/', views.justificativa_edit, name='justificativa_edit'),
	path('reabrir/<int:pk>/', views.justificativa_reabrir, name='justificativa_reabrir'),
	path('excluir/<int:pk>/', views.justificativa_excluir, name='justificativa_excluir'),
]

frequencia/relatorios/urls.py
from django.urls import path

from frequencia.relatorios import views

app_name = 'relatorios'
urlpatterns = [
	#Tipos de justificativa
	path('', views.busca_relatorio, name='busca_relatorio'),
	path('mensal/', views.relatorio_mensal, name='relatorio_mensal'),
	path('mensal/<int:pk>/', views.relatorio_mensal, name='relatorio_mensal'),
	path('geral/', views.listagem_geral, name='listagem_geral'),
	path('setor/', views.busca_setor, name='busca_setor'),
	path('setor/<int:pk>/', views.relatorio_setor, name='relatorio_setor'),
]

frequencia/urls.py
from django.urls import path
from django.conf import settings
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('frequencia.core.urls', namespace='core')),
    path('registro/', include('frequencia.registro.urls', namespace='registro')),
    path('vinculos', include('frequencia.vinculos.urls', namespace='vinculos')),
    path('calendario/', include('frequencia.calendario.urls', namespace='calendario')),
    path('justificativas/', include('frequencia.justificativas.urls', namespace='justificativas')),
    path('relatorios/', include('frequencia.relatorios.urls', namespace='relatorios')),
    path('conta/', include('frequencia.accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

# urlpatterns = [
#     url(r'^', include('frequencia.core.urls', namespace='core')),
#     url(r'^registro/', include('frequencia.registro.urls', namespace='registro')),
#     url(r'^vinculos/', include('frequencia.vinculos.urls', namespace='vinculos')),
#     url(r'^calendario/', include('frequencia.calendario.urls', namespace='calendario')),
# 	url(r'^justificativas/', include('frequencia.justificativas.urls', namespace='justificativas')),
# 	url(r'^relatorios/', include('frequencia.relatorios.urls', namespace='relatorios')),

#     url(r'^admin/', admin.site.urls),
#     url(r'^conta/', include('frequencia.accounts.urls', namespace='accounts')),
# ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frequencia/core/forms.py
from datetime import date

from django import forms

class NovaMensagemForm(forms.Form):

	texto = forms.CharField(widget=forms.Textarea, max_length=2000)
	
	def __init__(self, setores, *args, **kwargs):
		super(NovaMensagemForm, self).__init__(*args, **kwargs)

		#Popular listagem de setores		
		self.fields['setores'] = forms.ModelMultipleChoiceField(
									required=True, 
									queryset=setores, 
									label='Setor', 
									help_text='Selecione os setores para o envio da mensagem')

frequencia/core/views.py
import datetime
from datetime import timedelta

from rules.contrib.views import PermissionRequiredMixin

from django.urls import reverse
from django.db.models import Count
from django.shortcuts import redirect
from django.views.generic import FormView
from django.views.generic.base import TemplateView
from django.core.exceptions import PermissionDenied
from rules.contrib.views import permission_required
from django.http.response import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin

from frequencia.calendario.calendar import FeriadosRioGrandeDoNorte
from frequencia.vinculos.utils import get_bolsistas, get_setores, get_bolsistas_setor
from frequencia.vinculos.models import Vinculo
from frequencia.justificativas.models import JustificativaFalta
from frequencia.registro.models import Frequencia
from frequencia.core.mail import send_mail_text
from frequencia.relatorios.calculos import get_balanco_mes, get_balanco_mes_anterior
from .forms import NovaMensagemForm

def index(request):
	return redirect('registro:registro')

class HomeTemplateView(LoginRequiredMixin, TemplateView):	
	

	def __init__(self, **kwargs):
		super(HomeTemplateView, self).__init__(**kwargs)

		self.calendario = FeriadosRioGrandeDoNorte()
		self.data_atual = datetime.datetime.now()

	def dispatch(self, request, *args, **kwargs):		
		self.user = self.request.user				
		return super(HomeTemplateView, self).dispatch(request, *args, **kwargs)

	def get_bolsistas_por_setor(self):
		setores = get_setores(self.user)

		return Vinculo.objects.filter(
						group__name="Bolsista", 
						ativo=True, 
						user__is_active=True, 
						setor__in=setores).annotate(numero_bolsistas=Count('setor')).order_by('setor')

	def get_justificativas_pendentes(self):
		return JustificativaFalta.objects.filter(status=0, vinculo__in=self.bolsistas).count()

	def get_ultimos_registros(self):
		return Frequencia.objects.filter(bolsista__in=self.bolsistas).order_by('-pk')[:10]

	def get_num_bolsistas_trabalhando(self):
		data_hoje = self.data_atual.date()
		num_bolsistas_dia = Frequencia.objects.filter(created_at__date=data_hoje, 
													  tipo=0,
													  bolsista__in=self.bolsistas).count()
		return num_bolsistas_dia

	def get_bolsas_expirando(self):
		hoje = datetime.datetime.now().date()
		dia_final = hoje + timedelta(days=90)
		return self.bolsistas.filter(group__name='Bolsista',
									 ativo=True,
									 user__is_active=True,
									 termino_vigencia__lte=dia_final)

	def get_context_data(self, **kwargs):
		context = super(HomeTemplateView, self).get_context_data(**kwargs)
		self.bolsistas = get_bolsistas(self.user)

		context['dias_uteis'] = self.calendario.count_working_days_month(self.data_atual.month, self.data_atual.year)
		context['ultimos_registros'] = self.get_ultimos_registros()
		context['justificativas'] = self.get_justificativas_pendentes() or None

		if self.user.has_perm('accounts.is_servidor'):		
			self.template_name = 'home/home_servidor.html'	
			context['num_bolsistas_trabalhando'] = self.get_num_bolsistas_trabalhando()
			context['bolsas_expirando'] = self.get_bolsas_expirando()

			if self.user.has_perm('accounts.is_gestor_coordenador'):				
				context['bolsistas_por_setor'] = self.get_bolsistas_por_setor()
			elif self.user.has_perm('accounts.is_chefe'):						
				context['bolsistas_setor'] = self.bolsistas

		elif self.user.has_perm('accounts.is_bolsista'):
			self.template_name = 'home/home_bolsista.html'
			bolsista = self.bolsistas.first()
			balanco_mes = get_balanco_mes(bolsista, self.data_atual.month, self.data_atual.year)
			balanco_mes_anterior = get_balanco_mes_anterior(bolsista, self.data_atual.month, self.data_atual.year)

			context['dados_bolsista'] = bolsista
			context['balanco_mes'] = balanco_mes + balanco_mes_anterior
			context['ultimos_registros'] = context['ultimos_registros'][:6]

		else:
			self.template_name = 'home/home_externo.html'
		
		return context

class EnviarMensagemTemplateView(PermissionRequiredMixin, SuccessMessageMixin, FormView):

	template_name = 'nova_mensagem.html'
	form_class = NovaMensagemForm
	permission_required = 'accounts.is_servidor'
	success_message = 'Mensagem enviada com sucesso para todos os bolsistas do(s) seguinte(s) setor(es): %s'

	def get_form_kwargs(self):
		kwargs = super(EnviarMensagemTemplateView, self).get_form_kwargs()
		kwargs.update({'setores' : get_setores(self.request.user)})
		return kwargs

	def form_valid(self, form):
		self.setores = form.cleaned_data['setores']
		self.texto = form.cleaned_data['texto']

		for setor in self.setores:				
			if not self.request.user.has_perm('vinculo.is_setor_chefe', setor):
				raise PermissionDenied()

		emails_bolsistas = get_bolsistas_setor(self.setores).values_list('user__email', flat=True)
		subject = f'Nova mensagem de {self.request.user}'

		send_mail_text(subject, self.texto, emails_bolsistas)

		return super(EnviarMensagemTemplateView, self).form_valid(form)

	def get_success_url(self):		
		url = reverse('core:nova_mensagem')
		return url

	def get_success_message(self, cleaned_data):
		return self.success_message % ', '.join(self.setores.values_list('nome', flat=True))

home = HomeTemplateView.as_view()
nova_mensagem = EnviarMensagemTemplateView.as_view()

frequencia/core/templates/home/home_bolsista.html
{% extends 'base.html' %}

{% block content %}

{% load filtros %}
{% load timedelta_filter %}

{% load rules %}

<div class="row">
    <div class="col-xl-4 col-sm-6 mb-3">
      <div class="card text-white bg-success o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fa fa-fw fa-calendar"></i>
          </div>
          <div class="mr-5">{{dias_uteis}} dias úteis no mês de {% now "F" %}</div>
        </div>
        <a class="card-footer text-white clearfix small z-1" href="{% url 'calendario:feriados' %}">
          <span class="float-left">Calendário</span>
          <span class="float-right">
            <i class="fa fa-angle-right"></i>
          </span>
        </a>
      </div>
    </div>
    
    <div class="col-xl-4 col-sm-6 mb-3">
      <div class="card text-white bg-danger o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fa fa-fw fa-comment"></i>
          </div>
          <div class="mr-5">{{justificativas|default_if_none:"Nenhuma"}} {% if justificativas %}J{% else %}j{% endif %}ustificativa{{justificativas|pluralize}} de falta pendente{{justificativas|pluralize}} de homologação</div>
        </div>
        <a class="card-footer text-white clearfix small z-1" href="{% url 'justificativas:justificativas' %}">
          <span class="float-left">Justificativas</span>
          <span class="float-right">
            <i class="fa fa-angle-right"></i>
          </span>
        </a>
      </div>
    </div>
    
    <div class="col-xl-4 col-sm-6 mb-3">
      <div class="card text-white bg-primary o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fa fa-fw fa-users"></i>
          </div>
          <div class="mr-5">
            Saldo do mês atual:
            {% if balanco_mes.total_seconds > 0 %}
            -{{balanco_mes|timedelta:"{hours_total}:{minutes2}:{seconds2}"}}
            {% else %}
            {{balanco_mes|inverso|timedelta:"{hours_total}:{minutes2}:{seconds2}"}}
            {% endif %}
          </div>
        </div>
        <a class="card-footer text-white clearfix small z-1" href="{% url 'relatorios:relatorio_mensal' %}">
          <span class="float-left">Relatório mensal</span>
          <span class="float-right">
            <i class="fa fa-angle-right"></i>
          </span>
        </a>
      </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-8">
      <!-- Example Bar Chart Card-->
        <div class="card mb-3">
          <div class="card-header">
            <i class="fa fa-user"></i> Dados do usuário</div>
          <div class="card-body">
              <strong>Nome:</strong> {{ dados_bolsista.user.name }}<br>      
              <strong>CPF:</strong> {{ dados_bolsista.user.cpf }}<br>          
              <strong>Setor:</strong> {{ dados_bolsista.setor }}<br>              
              <strong>Turno:</strong> {{ dados_bolsista.get_turno_display }}<br>            
              <strong>Carga horária diária:</strong> {{ dados_bolsista.carga_horaria_diaria }}h<br>
              {% if dados_bolsista.inicio_vigencia and dados_bolsista.termino_vigencia %}            
                <strong>Vigência da bolsa:</strong> {{ dados_bolsista.inicio_vigencia|date:"d/m/Y" }} - {{ dados_bolsista.termino_vigencia|date:"d/m/Y" }}<br>  
              {% endif %}            
          </div>        
        </div>    
    </div>
    <div class="col-lg-4">

      <div class="card mb-3 sm-12">
        <div class="card-header">
          <i class="far fa-clock"></i> Últimos registros de ponto
        </div>          
          <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Data</th>
                            <th>Bolsista</th>                            
                            <th>Tipo</th>                            
                        </tr>
                    </thead>
                    <tbody>
                      {% if ultimos_registros %}
                        {% for registro in ultimos_registros %}
                            <tr>
                                <td>{{ registro.created_at|date:"d/m/Y H:i:s" }}</td>
                                <td>{{ registro.bolsista.user }}</td>
                                <td>{{ registro.get_tipo_display }}</td>
                            </tr>   
                        {% endfor %}
                      {% else %} 
                            <tr colspan="3"></tr>
                      {% endif %}
                    </tbody>
                </table>
            </div>
          </div>
        <div class="card-footer small text-muted">Última checagem às {% now "H:i:s" %}</div>
      </div>
        
    </div>
  </div>

{% endblock %}

frequencia/core/templates/home/home_externo.html
{% extends 'base.html' %}

{% block content %}

{% load filtros %}

{% load rules %}

<div class="row">
    <div class="col-xl-6 col-sm-6 mb-3">
      <div class="card text-white bg-success o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="far fa-calendar-alt"></i>
          </div>
          <div class="mr-5">{{dias_uteis}} dias úteis no mês de {% now "F" %}</div>
        </div>
        <a class="card-footer text-white clearfix small z-1" href="{% url 'calendario:feriados' %}">
          <span class="float-left">Calendário</span>
          <span class="float-right">
            <i class="fa fa-angle-right"></i>
          </span>
        </a>
      </div>
    </div>    
    
</div>

<div class="row">
    <div class="col-lg-6">
      <!-- Example Bar Chart Card-->
        <div class="card mb-3">
          <div class="card-header">
            <i class="fa fa-user"></i> Dados do usuário</div>
          <div class="card-body">
              <strong>Nome:</strong> {{ request.user.name }}<br>      
              <strong>Login:</strong> {{ request.user.username }}<br>              
              <strong>Email:</strong> {{ request.user.email }}<br>      
              <strong>CPF:</strong> {{ request.user.cpf }}<br>             
              <strong>Usuário sem vínculos ativos</strong><br>
          </div>        
        </div>    
    </div>
  </div>

{% endblock %}

frequencia/core/templates/home/home_servidor.html
{% extends 'base.html' %}

{% block content %}

{% load rules %}
{% has_perm 'accounts.is_gestor_coordenador' user as is_gestor_coordenador %}
{% has_perm 'accounts.is_gestor' user as is_gestor %}

<div class="row">
    <div class="col-xl-4 col-sm-6 mb-3">
      <div class="card text-white bg-success o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="far fa-calendar-alt"></i>
          </div>
          <div class="mr-5">{{dias_uteis}} Dias úteis no mês de {% now "F" %}</div>
        </div>
        <a class="card-footer text-white clearfix small z-1" href="{% url 'calendario:feriados' %}">
          <span class="float-left">Calendário</span>
          <span class="float-right">
            <i class="fa fa-angle-right"></i>
          </span>
        </a>
      </div>
    </div>
    
    <div class="col-xl-4 col-sm-6 mb-3">
      <div class="card text-white bg-danger o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fa fa-fw fa-comment"></i>
          </div>
          <div class="mr-5">{{justificativas|default_if_none:"Nenhuma"}} {% if justificativas %}J{% else %}j{% endif %}ustificativa{{justificativas|pluralize}} de falta pendente{{justificativas|pluralize}} de homologação</div>
        </div>
        <a class="card-footer text-white clearfix small z-1" href="{% url 'justificativas:justificativas' %}">
          <span class="float-left">Ver detalhes</span>
          <span class="float-right">
            <i class="fa fa-angle-right"></i>
          </span>
        </a>
      </div>
    </div>
    
    <div class="col-xl-4 col-sm-6 mb-3">
      <div class="card text-white bg-primary o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fa fa-fw fa-users"></i>
          </div>
          <div class="mr-5">{{num_bolsistas_trabalhando}} Registro{{num_bolsistas_trabalhando|pluralize}} de frequência hoje</div>
        </div>
        <a class="card-footer text-white clearfix small z-1" href="{% url 'relatorios:listagem_geral' %}">
          <span class="float-left">Listagem geral</span>
          <span class="float-right">
            <i class="fa fa-angle-right"></i>
          </span>
        </a>
      </div>
    </div>
</div>

<div class="row">
    {% if bolsas_expirando %}
      <div class="col-lg-12">
        <div class="card mb-3">
            <div class="card-header">
              <i class="fa fa-user-times"></i> Bolsas expirando nos próximos 90 dias</div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Bolsista</th>
                                <th>Vigência da bolsa</th>
                                <th>Tempo restante</th>
                                <th>Setor</th>
                                {% if is_gestor %}
                                  <th></th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for bolsista in bolsas_expirando %}
                                <tr {% if bolsista.bolsa_expirada %} class="text-danger" {% endif %}>
                                    <td>{{ bolsista.user.name }}</td>
                                    <td>{{ bolsista.inicio_vigencia|date:"d/m/Y" }} - {{ bolsista.termino_vigencia|date:"d/m/Y" }}</td>
                                    {% if bolsista.bolsa_expirada %}
                                      <td>Expirado</td>                                    
                                    {% else %}
                                      <td>{{ bolsista.termino_vigencia|timeuntil }}</td>
                                    {% endif %}
                                    <td>{{ bolsista.setor }}</td>
                                    {% if is_gestor %}
                                      <td><a href="{% url 'accounts:accounts_edit' bolsista.user.pk %}"><i class="fas fa-pencil-alt pull-right"></i></a></td>
                                    {% endif %}
                                </tr>   
                            {% endfor %}                        
                        </tbody>                    
                    </table>
                </div>
            </div>        
          </div>     
        </div>
    {% endif %}

    <div class="col-lg-8">
      <!-- Example Bar Chart Card-->
      {% if is_gestor_coordenador %}
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-chart-pie"></i> Distribuição de bolsistas por setor</div>
          <div class="card-body">
              {% regroup bolsistas_por_setor by setor as setores %}             

              <div id="accordion-bolsistas"> 
                {% for setor, bolsistas in setores %}
                  <div class="card">
                    <div class="card-header" id="headingOne">
                      <h5 class="mb-0">
                        <button class="btn btn-link" data-toggle="collapse" data-target="#s{{setor.pk}}" aria-expanded="true" aria-controls="collapseOne">
                            {{ setor }}
                        </button>
                        <span class="badge badge-pill badge-secondary float-right">{{ bolsistas|length }}</span>
                      </h5>
                    </div>
                    
                    <div id="s{{setor.pk}}" class="collapse bolsistas" data-parent="#accordion-bolsistas">
                      <div class="card-body">
                          <table class="table">
                              <thead>
                                  <tr>                          
                                      <th>Nome</th>                          
                                      <th>Login</th>                          
                                      <th>CPF</th>                           
                                      <th>E-mail</th>                          
                                      {% if is_gestor %}
                                        <th></th>
                                      {% endif %}
                                  </tr>
                              </thead>
                              <tbody>
                                  {% for bolsista in bolsistas %}
                                      <tr>
                                          <td>{{ bolsista.user.name }}</td>                       
                                          <td>{{ bolsista.user.username }}</td>
                                          <td>{{ bolsista.user.cpf }}</td>
                                          <td>{{ bolsista.user.email }}</td>
                                          {% if is_gestor %}
                                            <td><a href="{% url 'accounts:accounts_edit' bolsista.user.pk %}"><i class="fas fa-pencil-alt pull-right"></i></a></td>
                                          {% endif %}
                                      </tr>
                                  {% endfor %}
                              </tbody>
                          </table>                        
                      </div>
                    </div>
                  </div>                
                {% endfor %}
              </div>
          </div>        
        </div>        
      {% else %}
        <div class="card mb-3">
          <div class="card-header">
            <i class="fa fa-users"></i> Bolsistas no setor</div>
          <div class="card-body">
              <div class="table-responsive">
                  <table class="table table-hover">
                      <thead>
                          <tr>
                              <th>Bolsista</th>
                              <th>Email</th>
                              <th class="text-center">Início da bolsa</th>
                              <th>Turno</th>
                          </tr>
                      </thead>
                      <tbody>
                          {% for bolsista in bolsistas_setor %}
                              <tr>
                                  <td>{{ bolsista.user.name }}</td>
                                  <td>{{ bolsista.user.email }}</td>
                                  <td class="text-center">{{ bolsista.inicio_vigencia|date:"d/m/Y" }} <br> {{ bolsista.termino_vigencia|date:"d/m/Y" }}</td>
                                  <td>{{ bolsista.get_turno_display }}</td>
                              </tr>   
                          {% endfor %}
                      </tbody>
                  </table>
              </div>
          </div>        
        </div>   
      {% endif %}     
    </div>
    <div class="col-lg-4">

      <div class="card mb-3 sm-12">
        <div class="card-header">
          <i class="far fa-clock"></i> Últimos registros de ponto
        </div>          
          <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Data</th>
                            <th>Bolsista</th>                            
                            <th>Tipo</th>                            
                        </tr>
                    </thead>
                    <tbody>
                        {% for registro in ultimos_registros %}
                            <tr>
                                <td>{{ registro.created_at|date:"d/m/Y H:i:s" }}</td>
                                <td>{{ registro.bolsista.user }}</td>
                                <td>{{ registro.get_tipo_display }}</td>
                            </tr>   
                        {% endfor %}  
                    </tbody>
                </table>
            </div>
          </div>
        <div class="card-footer small text-muted">Última checagem às {% now "H:i:s" %}</div>
      </div>
        
    </div>
  </div>

{% endblock %}

{% block extra-scripts %}
    <script type="text/javascript">
        $(document).ready(function(){
          $('.bolsistas:first').collapse("show");
        });
    </script>
{% endblock %}