frequencia/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.urls import path

from frequencia.accounts import views

app_name = 'accounts'
urlpatterns = [
	path('entrar/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
	path('sair/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_URL), name='logout'),
	
	path('usuarios/', views.accounts, name='accounts'),
	path('usuario/novo/', views.accounts_create, name='accounts_create'),
	path('usuario/editar/<int:pk>/', views.accounts_edit, name='accounts_edit'),
	path('usuario/editar_senha/', views.edit_password, name='edit_password'),
	path('usuario/redefinir_senha/<int:pk>/', views.reset_password, name='reset_password'),
]

frequencia/calendario/urls.py
from django.urls import path

from frequencia.calendario import views

app_name = 'calendario'
urlpatterns = [
	#Feriados
	path('', views.feriados, name='feriados'),
	path('<int:ano>', views.feriados, name='feriados'),
	path('feriado/novo/', views.feriado_create, name='feriado_create'),
	path('feriado/remover/<int:pk>', views.feriado_remove, name='feriado_remove'),
]

frequencia/core/urls.py
from django.urls import path

from frequencia.core import views

app_name = 'core'
urlpatterns = [
	path('', views.index, name='index'),
	path('home/', views.home, name='home'),
	path('nova-mensagem/', views.nova_mensagem, name='nova_mensagem'),
]

frequencia/registro/urls.py
from django.urls import path

from frequencia.registro import views

app_name = 'registro'
urlpatterns = [
	#Máquinas
	path('maquinas/', views.maquinas, name='maquinas'),
	path('maquina/novo/', views.maquina_create, name='maquina_create'),
	path('maquina/editar/<int:pk>/', views.maquina_edit, name='maquina_edit'),
	path('maquina/remover/<int:pk>/', views.maquina_remove, name='maquina_remove'),

	#Registro
	path('', views.registro, name='registro'),
	path('registros_dia/', views.registros_dia, {'Bolsista': None}, name='registros_dia'),
    path('api/', views.registro_api, name='registro_api')
]

frequencia/urls.py
from django.urls import path
from django.conf import settings
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('frequencia.core.urls', namespace='core')),
    path('registro/', include('frequencia.registro.urls', namespace='registro')),
    path('vinculos', include('frequencia.vinculos.urls', namespace='vinculos')),
    path('calendario/', include('frequencia.calendario.urls', namespace='calendario')),
    path('justificativas/', include('frequencia.justificativas.urls', namespace='justificativas')),
    path('relatorios/', include('frequencia.relatorios.urls', namespace='relatorios')),
    path('conta/', include('frequencia.accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

# urlpatterns = [
#     url(r'^', include('frequencia.core.urls', namespace='core')),
#     url(r'^registro/', include('frequencia.registro.urls', namespace='registro')),
#     url(r'^vinculos/', include('frequencia.vinculos.urls', namespace='vinculos')),
#     url(r'^calendario/', include('frequencia.calendario.urls', namespace='calendario')),
# 	url(r'^justificativas/', include('frequencia.justificativas.urls', namespace='justificativas')),
# 	url(r'^relatorios/', include('frequencia.relatorios.urls', namespace='relatorios')),

#     url(r'^admin/', admin.site.urls),
#     url(r'^conta/', include('frequencia.accounts.urls', namespace='accounts')),
# ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frequencia/vinculos/urls.py
from django.urls import path

from frequencia.vinculos import views

app_name = 'vinculos'
urlpatterns = [
	path('setores-coordenadorias/', views.setores_coordenadorias, name='setores_coordenadorias'),

	#Setores
	path('setor/novo/', views.setor_create, name='setor_create'),
	path('setor/editar/<int:pk>/', views.setor_edit, name='setor_edit'),

	#Coordenadorias
	path('coordenadoria/novo/', views.coordenadoria_create, name='coordenadoria_create'),
	path('coordenadoria/editar/<int:pk>/', views.coordenadoria_edit, name='coordenadoria_edit'),
]

frequencia/core/forms.py
from datetime import date

from django import forms

class NovaMensagemForm(forms.Form):

	texto = forms.CharField(widget=forms.Textarea, max_length=2000)
	
	def __init__(self, setores, *args, **kwargs):
		super(NovaMensagemForm, self).__init__(*args, **kwargs)

		#Popular listagem de setores		
		self.fields['setores'] = forms.ModelMultipleChoiceField(
									required=True, 
									queryset=setores, 
									label='Setor', 
									help_text='Selecione os setores para o envio da mensagem')

frequencia/core/views.py
import datetime
from datetime import timedelta

from rules.contrib.views import PermissionRequiredMixin

from django.urls import reverse
from django.db.models import Count
from django.shortcuts import redirect
from django.views.generic import FormView
from django.views.generic.base import TemplateView
from django.core.exceptions import PermissionDenied
from rules.contrib.views import permission_required
from django.http.response import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin

from frequencia.calendario.calendar import FeriadosRioGrandeDoNorte
from frequencia.vinculos.utils import get_bolsistas, get_setores, get_bolsistas_setor
from frequencia.vinculos.models import Vinculo
from frequencia.justificativas.models import JustificativaFalta
from frequencia.registro.models import Frequencia
from frequencia.core.mail import send_mail_text
from frequencia.relatorios.calculos import get_balanco_mes, get_balanco_mes_anterior
from .forms import NovaMensagemForm

def index(request):
	return redirect('registro:registro')

class HomeTemplateView(LoginRequiredMixin, TemplateView):	
	

	def __init__(self, **kwargs):
		super(HomeTemplateView, self).__init__(**kwargs)

		self.calendario = FeriadosRioGrandeDoNorte()
		self.data_atual = datetime.datetime.now()

	def dispatch(self, request, *args, **kwargs):		
		self.user = self.request.user				
		return super(HomeTemplateView, self).dispatch(request, *args, **kwargs)

	def get_bolsistas_por_setor(self):
		setores = get_setores(self.user)

		return Vinculo.objects.filter(
						group__name="Bolsista", 
						ativo=True, 
						user__is_active=True, 
						setor__in=setores).annotate(numero_bolsistas=Count('setor')).order_by('setor')

	def get_justificativas_pendentes(self):
		return JustificativaFalta.objects.filter(status=0, vinculo__in=self.bolsistas).count()

	def get_ultimos_registros(self):
		return Frequencia.objects.filter(bolsista__in=self.bolsistas).order_by('-pk')[:10]

	def get_num_bolsistas_trabalhando(self):
		data_hoje = self.data_atual.date()
		num_bolsistas_dia = Frequencia.objects.filter(created_at__date=data_hoje, 
													  tipo=0,
													  bolsista__in=self.bolsistas).count()
		return num_bolsistas_dia

	def get_bolsas_expirando(self):
		hoje = datetime.datetime.now().date()
		dia_final = hoje + timedelta(days=90)
		return self.bolsistas.filter(group__name='Bolsista',
									 ativo=True,
									 user__is_active=True,
									 termino_vigencia__lte=dia_final)

	def get_context_data(self, **kwargs):
		context = super(HomeTemplateView, self).get_context_data(**kwargs)
		self.bolsistas = get_bolsistas(self.user)

		context['dias_uteis'] = self.calendario.count_working_days_month(self.data_atual.month, self.data_atual.year)
		context['ultimos_registros'] = self.get_ultimos_registros()
		context['justificativas'] = self.get_justificativas_pendentes() or None

		if self.user.has_perm('accounts.is_servidor'):		
			self.template_name = 'home/home_servidor.html'	
			context['num_bolsistas_trabalhando'] = self.get_num_bolsistas_trabalhando()
			context['bolsas_expirando'] = self.get_bolsas_expirando()

			if self.user.has_perm('accounts.is_gestor_coordenador'):				
				context['bolsistas_por_setor'] = self.get_bolsistas_por_setor()
			elif self.user.has_perm('accounts.is_chefe'):						
				context['bolsistas_setor'] = self.bolsistas

		elif self.user.has_perm('accounts.is_bolsista'):
			self.template_name = 'home/home_bolsista.html'
			bolsista = self.bolsistas.first()
			balanco_mes = get_balanco_mes(bolsista, self.data_atual.month, self.data_atual.year)
			balanco_mes_anterior = get_balanco_mes_anterior(bolsista, self.data_atual.month, self.data_atual.year)

			context['dados_bolsista'] = bolsista
			context['balanco_mes'] = balanco_mes + balanco_mes_anterior
			context['ultimos_registros'] = context['ultimos_registros'][:6]

		else:
			self.template_name = 'home/home_externo.html'
		
		return context

class EnviarMensagemTemplateView(PermissionRequiredMixin, SuccessMessageMixin, FormView):

	template_name = 'nova_mensagem.html'
	form_class = NovaMensagemForm
	permission_required = 'accounts.is_servidor'
	success_message = 'Mensagem enviada com sucesso para todos os bolsistas do(s) seguinte(s) setor(es): %s'

	def get_form_kwargs(self):
		kwargs = super(EnviarMensagemTemplateView, self).get_form_kwargs()
		kwargs.update({'setores' : get_setores(self.request.user)})
		return kwargs

	def form_valid(self, form):
		self.setores = form.cleaned_data['setores']
		self.texto = form.cleaned_data['texto']

		for setor in self.setores:				
			if not self.request.user.has_perm('vinculo.is_setor_chefe', setor):
				raise PermissionDenied()

		emails_bolsistas = get_bolsistas_setor(self.setores).values_list('user__email', flat=True)
		subject = f'Nova mensagem de {self.request.user}'

		send_mail_text(subject, self.texto, emails_bolsistas)

		return super(EnviarMensagemTemplateView, self).form_valid(form)

	def get_success_url(self):		
		url = reverse('core:nova_mensagem')
		return url

	def get_success_message(self, cleaned_data):
		return self.success_message % ', '.join(self.setores.values_list('nome', flat=True))

home = HomeTemplateView.as_view()
nova_mensagem = EnviarMensagemTemplateView.as_view()

frequencia/core/templates/base.html
{% load static %}
{% load simpletags %}
{% load compress %}

{% load rules %}
{% has_perm 'accounts.is_servidor' user as is_servidor %}
{% has_perm 'accounts.is_gestor' user as is_gestor %}
{% has_perm 'accounts.is_bolsista' user as is_bolsista %}

<!DOCTYPE html>
<html lang="en">

  {% include "head.html" %}

  {% block extra-css %}{% endblock %} 
  

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
  <!-- SIDENAV -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="{% url 'core:home' %}">
      <img src="{% static 'images/bczm-logo.png' %}" class="logo-nav">
      Frequência BCZM
    </a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="sideAccordion">
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="{% url 'core:home' %}">
            <i class="fa fa-fw fa-home"></i>
            <span class="nav-link-text">Home</span>
          </a>
        </li>
        {% if is_gestor %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'vinculos:setores_coordenadorias' %}">
            <i class="fa fa-fw fa-cubes"></i>
            <span class="nav-link-text">Setores</span>
          </a>
        </li>
        {% endif %}

        {% if user.is_superuser %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'registro:maquinas' %}">
            <i class="fa fa-fw fa fa-desktop"></i>
            <span class="nav-link-text">Máquinas</span>
          </a>
        </li>
        {% endif %}

        {% if is_gestor %}
        <li class="nav-item">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseUsuarios" data-parent="#sideAccordion">
            <i class="fa fa-fw fa-users"></i>
            <span class="nav-link-text">Usuários</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseUsuarios">
            <li><a href="{% url 'accounts:accounts' %}">Listar</a></li>
            <li><a href="{% url 'accounts:accounts_create' %}">Novo usuário</a></li>
          </ul>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseJustificativas" data-parent="#sideAccordion">
            <i class="far fa-comment"></i>
            <span class="nav-link-text">Justificativas</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseJustificativas">
            <li><a href="{% url 'justificativas:justificativas' %}">Listar</a></li>
            {% if is_bolsista %}
            <li><a href="{% url 'justificativas:justificativa_create' %}">Nova justificativa</a></li>
            {% endif %}
            {% if is_gestor %}
            <li><a href="{% url 'justificativas:tipo_justificativa' %}">Gerenciar tipos</a></li>
            {% endif %}
          </ul>
        </li>       

        <li class="nav-item">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseRelatorios" data-parent="#sideAccordion">
            <i class="far fa-file-alt"></i>
            <span class="nav-link-text">Relatórios</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseRelatorios">
            <li><a href="{% url 'relatorios:busca_relatorio' %}">Relatório mensal</a></li>
            {% if is_servidor %}
            <li><a href="{% url 'relatorios:listagem_geral' %}">Listagem geral</a></li>
            <li><a href="{% url 'relatorios:busca_setor' %}">Relatório por setor</a></li>
            {% endif %}
          </ul>
        </li>

        {% if is_servidor %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:nova_mensagem' %}">            
            <i class="fas fa-bullhorn"></i>
            <span class="nav-link-text">Mensagem</span>
          </a>
        </li>
        {% endif %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'calendario:feriados' %}">            
            <i class="far fa-calendar-alt"></i>
            <span class="nav-link-text">Calendário</span>
          </a>
        </li>              
      </ul>
      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
      </ul>

      <!-- TOPNAV -->
      <ul class="navbar-nav ml-auto">        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle mr-lg-2" href="#" data-toggle="dropdown">
            <i class="fa fa-fw fa-user"></i>
            <span class="d-lg-none">Usuário</span>
            <!--span class="indicator text-warning d-none d-lg-block">
              <i class="fa fa-fw fa-circle"></i>
            </span-->
          </a>
          <div class="dropdown-menu dropdown-menu-right">
            <h6 class="dropdown-header">{{ user }}</h6>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'accounts:edit_password' %}">
              <span>
                <strong>
                  <i class="fa fa-key"></i> Alterar senha</strong>
              </span>              
              <div class="dropdown-message small">Clique para alterar a senha do seu usuário</div>
            </a>
            <a class="dropdown-item" href="{% url 'accounts:logout' %}">
              <span>
                <strong>
                  <i class="fas fa-sign-out-alt"></i> Sair do sistema</strong>
              </span>              
              <div class="dropdown-message small">Terminar a sessão atual</div>
            </a>  
          </div>
        </li>                
      </ul>
    </div>
  </nav>
  <div class="content-wrapper">
    <div class="container-fluid">
        {% if messages %}     
            {% for message in messages %}                
            <div id="alertMessages" style="display: none;">
                <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                  {{ message|safe }}
                </div>
            </div>
            {% endfor %}       
        {% endif %}
        {% block content%}

        {% endblock %}
    </div>
    <!-- /.container-fluid-->
    <!-- /.content-wrapper-->
    <footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
          <small> © Biblioteca Central Zila Mamede - {% now "Y" %} - Versão {% current_version %}</small>
        </div>
      </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded hidden-print" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>
  </div>

  {% compress js %}
    {% include "script.html" %}
    
    {% block extra-scripts %}{% endblock %}
  {% endcompress %}
</body>

</html>

frequencia/core/templates/head.html
{% load static %}
{% load compress %}

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Sistema de gerenciamento de frequências dos bolsistas da Biblioteca Central Zila Mamede">
  <meta name="author" content="Biblioteca Central Zila Mamede">
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
  <title>Frequência BCZM</title>

  {% compress css %}
  <!-- Bootstrap core CSS-->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome/css/all.min.css' %}" rel="stylesheet" type="text/css">

  <!-- Page level plugin CSS-->
  <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">
      
  <!--  Select2 CSS    -->
  <link href="{% static 'css/select2.min.css' %}" rel="stylesheet" />
  
  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">

  <link href="{% static 'css/datepicker.css' %}" rel="stylesheet">
  {% endcompress %}

</head> 

frequencia/core/templates/nova_mensagem.html
{% extends "base.html" %}

{% load static %}
{% load rules %}
{% load widget_tweaks %}

{% block extra-css %}
	<link href="{% static 'vendor/summernote/summernote-lite.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
	
	{% has_perm 'accounts.is_gestor' user as is_gestor %}
	
	<div class="card mb-3">
	    <div class="card-header">
				<i class="fas fa-bullhorn"></i> Enviar email para os bolsistas do setor
	    </div>
	    <div class="card-body">
            <form action="#" method="post">
                 {% csrf_token %}

                 {% if form.non_field_errors %}
					<div class="alert alert-danger">
						{% for error in form.non_field_errors %}
							{{ error }}
						{% endfor %}
					</div>
				{% endif %}
				
				<div class="row">
					{% if is_gestor %}	
					<div class="col-md-12">
							<div class="form-check form-check-inline">
								<input type="checkbox" class="form-check-input" id="todos_bolsistas" name="todos_bolsistas">
								<label for="todos_bolsistas" class="form-check-label">Todos os setores</label>
							</div>		
					</div>
					{% endif %}
					<div class="form-group col-md-12" id="select_setores">
						<label class="control-label">{{form.setores.label}}</label>
						{% render_field form.setores class="form-control" required="" %}					
						{% if form.setores.errors %}
	                        <label class="text-danger">{{ form.setores.errors.0 }}</label>
	                    {% endif %}
					</div>

					<div class="form-group col-md-12">
						<label class="control-label">{{form.texto.label}}</label>
						{% render_field form.texto class="form-control" required="" id="html-editor" %}
						{% if form.texto.errors %}
							<label class="text-danger">{{ form.texto.errors.0 }}</label>
						{% endif %}
					</div>
									
                </div>
			    <div class="text-center">
				    <button class="btn btn-info" class="enviar_mensagem">Enviar</button>
				</div>		
            </form>
        </div>
    </div> 

{% endblock %}

{% block extra-scripts %}
	<script src="{% static 'vendor/summernote/summernote-lite.js' %}"></script>
	<script src="{% static 'vendor/summernote/lang/summernote-pt-BR.min.js' %}"></script>
	<script type="text/javascript">
		$('select').select2({
			width: '100%',
			placeholder: "{{ form.setores.help_text }}",
		});
		$('#html-editor').summernote({
			lang: 'pt-BR',
			height: 350,
			toolbar: [				
				['style', ['bold', 'italic', 'underline', 'clear']],				
				['fontsize', ['fontsize']],			
				['color', ['color']],
				['para', ['ul', 'ol', 'paragraph']]
			]
		});
		$('#todos_bolsistas').change(function() {
			var selectedItems = [];			
        	if($(this).is(":checked")) {				
				var allOptions = $("#id_setores option");
				allOptions.each(function() {
					selectedItems.push( $(this).val() );
				});						
			}
			$("#id_setores").val(selectedItems).trigger("change");
		});
		
	</script>
{% endblock %}

frequencia/core/templates/script.html
{% load static %}

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/popper/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- Page level plugin JavaScript-->
<script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

<script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>

<!-- Datetime picker -->
<script src="{% static 'js/datepicker.js'%}"></script>

<!-- Select2 -->
<script src="{% static 'js/select2.min.js'%}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin.min.js' %}"></script>

<!-- Custom scripts for this page-->
<script src="{% static 'js/sb-admin-datatables.min.js' %}"></script>


<script type="text/javascript">          
    $(document).ready(function () {
       $("#alertMessages").show(300);
    });
</script>