frequencia/justificativas/urls.py
from django.urls import path

from frequencia.justificativas import views

app_name = 'justificativas'
urlpatterns = [
	#Tipos de justificativa
	path('tipos/', views.tipo_justificativa, name='tipo_justificativa'),
	path('tipo/novo/', views.tipo_justificativa_create, name='tipo_justificativa_create'),
	path('tipo/editar/<int:pk>/', views.tipo_justificativa_edit, name='tipo_justificativa_edit'),
	path('tipo/remover/<int:pk>/', views.tipo_justificativa_remove, name='tipo_justificativa_remove'),

	#Justificativa de falta
	path('', views.justificativas, name='justificativas'),	
	path('novo/', views.justificativa_create, name='justificativa_create'),
	path('detalhes/<int:pk>/', views.justificativa_edit, name='justificativa_edit'),
	path('reabrir/<int:pk>/', views.justificativa_reabrir, name='justificativa_reabrir'),
	path('excluir/<int:pk>/', views.justificativa_excluir, name='justificativa_excluir'),
]

frequencia/urls.py
from django.urls import path
from django.conf import settings
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('frequencia.core.urls', namespace='core')),
    path('registro/', include('frequencia.registro.urls', namespace='registro')),
    path('vinculos', include('frequencia.vinculos.urls', namespace='vinculos')),
    path('calendario/', include('frequencia.calendario.urls', namespace='calendario')),
    path('justificativas/', include('frequencia.justificativas.urls', namespace='justificativas')),
    path('relatorios/', include('frequencia.relatorios.urls', namespace='relatorios')),
    path('conta/', include('frequencia.accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

# urlpatterns = [
#     url(r'^', include('frequencia.core.urls', namespace='core')),
#     url(r'^registro/', include('frequencia.registro.urls', namespace='registro')),
#     url(r'^vinculos/', include('frequencia.vinculos.urls', namespace='vinculos')),
#     url(r'^calendario/', include('frequencia.calendario.urls', namespace='calendario')),
# 	url(r'^justificativas/', include('frequencia.justificativas.urls', namespace='justificativas')),
# 	url(r'^relatorios/', include('frequencia.relatorios.urls', namespace='relatorios')),

#     url(r'^admin/', admin.site.urls),
#     url(r'^conta/', include('frequencia.accounts.urls', namespace='accounts')),
# ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frequencia/justificativas/models.py
from datetime import timedelta

from django.db import models
from django.db.models import Q
from django.conf import settings

from frequencia.core.basemodel import basemodel
from frequencia.core.mail import send_mail_template
from frequencia.vinculos.models import Vinculo
from frequencia.calendario.calendar import FeriadosRioGrandeDoNorte

from .validators import validate_file_extension

class TipoJustificativaFalta(basemodel):

	nome = models.CharField('Tipo', max_length=100)
	comprovante_obrigatorio = models.BooleanField('Comprovante obrigatório', blank=True, default=False)

	def __str__(self):
		return self.nome

	class Meta:
		verbose_name = 'Tipo de justificativa'
		verbose_name_plural = 'Tipos de justificativa'


class JustificativaFaltaManager(models.Manager):
	def buscar(self, query):
		if not query:
			return self
		return self.filter(Q(vinculo__user__name__icontains=query) | 
						   Q(descricao__icontains=query))

class JustificativaFalta(basemodel):

	objects = JustificativaFaltaManager()

	JUSTIFICATIVA_STATUS_CHOICES = (
		(0, 'Pendente'),
		(1, 'Indeferida'),
		(2, 'Deferida'),
	)

	tipo = models.ForeignKey(TipoJustificativaFalta, verbose_name='Tipo de justificativa', related_name='justificativas', on_delete=models.PROTECT)
	vinculo = models.ForeignKey(Vinculo, verbose_name='Vínculo', related_name='justificativas', on_delete=models.CASCADE)
	usuario_analise = models.ForeignKey(Vinculo, verbose_name='Analisado por', related_name='justificativas_homologadas', on_delete=models.PROTECT, blank=True, null=True)

	status = models.IntegerField('Status da justificativa', choices=JUSTIFICATIVA_STATUS_CHOICES, default=0)
	descricao = models.TextField('Descrição')
	inicio = models.DateField('Data de início')
	termino = models.DateField('Data de término')
	comprovante = models.FileField('Comprovante', blank=True, upload_to='anexos_justificativas/', validators=[validate_file_extension])

	parecer = models.TextField('Parecer da chefia', blank=True)
	horas_abonadas = models.DurationField('Tempo abonado', blank=True, null=True)

	@property
	def horas_sugeridas(self):
		calendario = FeriadosRioGrandeDoNorte()
		numero_dias_uteis = calendario.count_working_days(self.inicio, self.termino)
		horas_sugeridas = self.vinculo.carga_horaria_diaria * numero_dias_uteis

		if not horas_sugeridas:
			return timedelta()

		horas_sugeridas = timedelta(hours=horas_sugeridas)
		from frequencia.relatorios.calculos import get_total_horas_registradas_contabilizadas
		registros = self.vinculo.registros.filter(created_at__date__gte=self.inicio, 
												  created_at__date__lte=self.termino)
		horas_registradas, horas_contabilizadas = get_total_horas_registradas_contabilizadas(registros)

		horas_sugeridas = horas_sugeridas - horas_registradas
		return horas_sugeridas if horas_sugeridas.days >= 0 else timedelta()

	def __str__(self):
		return '{0} - {1}'.format(self.vinculo.user, self.descricao)

	class Meta:
		verbose_name = 'Justificativa de falta'
		verbose_name_plural = 'Justificativas de falta'


def post_save_justificativa(instance, created, **kwargs):
	if created:
		subject = 'Nova justificativa de falta cadastrada'
		context = { 'justificativa' : instance	, 'base_url': settings.BASE_URL_SERVER }
		template_name = 'justificativas/justificativa_mail.html'
		
		chefes = instance.vinculo.setor.vinculos.filter(group__name='Chefe de setor', ativo=True, user__is_active=True)		
		for chefe in chefes:
			recipient_list = [chefe.user.email]
			try:				
				send_mail_template(subject=subject, template_name=template_name, context=context, recipient_list=recipient_list)
			except:
				pass

models.signals.post_save.connect(
	post_save_justificativa, 
	sender=JustificativaFalta,
	dispatch_uid='post_save_justificativa'
)

frequencia/justificativas/forms.py
import re

from django import forms
from django.db.models import Q
from django.conf import settings
from django.core.validators import MaxLengthValidator

from .models import TipoJustificativaFalta, JustificativaFalta

class EditTipoJustificativaForm(forms.ModelForm):

	class Meta:
		model = TipoJustificativaFalta
		fields = ['nome', 'comprovante_obrigatorio']


class CreateJustificativaForm(forms.ModelForm):

	class Meta:
		model = JustificativaFalta
		fields = ['tipo', 'descricao', 'inicio', 'termino', 'comprovante']
		widgets = {
          'descricao': forms.Textarea(attrs={'rows':3, 'maxlength':2000}),
        }

	def __init__(self, *args, **kwargs):
		super(CreateJustificativaForm, self).__init__(*args, **kwargs)
		self.fields['tipo'].empty_label = ""
		self.fields['descricao'].validators = [MaxLengthValidator(2000)]		

	def clean_comprovante(self):
		comprovante = self.cleaned_data.get('comprovante', False)	
		max_upload_size = settings.MAX_UPLOAD_SIZE

		if comprovante and comprovante.size > max_upload_size:
			raise forms.ValidationError(['O tamanho do arquivo excede o limite máximo de 5MB.',])

		return comprovante

	def clean(self):
		cleaned_data = super(CreateJustificativaForm, self).clean()
		data_inicio = cleaned_data.get("inicio", '')
		data_termino = cleaned_data.get("termino", '')

		if data_inicio > data_termino:
			raise forms.ValidationError("Data de término deve ser posterior à data de inicio")

		tipo = cleaned_data.get("tipo", '')
		comprovante = self.cleaned_data.get('comprovante', False)
		if tipo.comprovante_obrigatorio and not comprovante:
			raise forms.ValidationError("Este tipo de justificativa exige o cadastro do comprovante de ausência")

		return cleaned_data

	def save(self, user, commit=True):
		justificativa = super(CreateJustificativaForm, self).save(commit=False)
		vinculos = user.vinculos.filter(ativo=True)
		if vinculos:
			justificativa.vinculo = vinculos.first()
		else:
			raise forms.ValidationError("Usuário não autorizado para cadastrar justificativa de falta")

		if commit:
			justificativa.save()

		return justificativa

class EditJustificativaForm(forms.ModelForm):

	class Meta:
		model = JustificativaFalta
		fields = ['status', 'parecer', 'horas_abonadas']
		widgets = {
			'parecer': forms.Textarea(attrs={'rows':3, 'maxlength':2000}),
		}

	def __init__(self, *args, **kwargs):
		super(EditJustificativaForm, self).__init__(*args, **kwargs)		
		self.fields['parecer'].validators = [MaxLengthValidator(2000)]

	def clean_horas_abonadas(self):
		horas = self.data['horas_abonadas']
		pattern = re.compile('^([0-9]){1,2}(:[0-5][0-9]){2}$')

		if horas is None or not pattern.search(str(horas)):
			raise forms.ValidationError(['O tempo abonado deve ser informado no formato HH:MM:SS',])
		return horas

	def clean_status(self):
		if not self.cleaned_data['status']:
			raise forms.ValidationError(['Status deve ser definido',])
		return self.cleaned_data['status']

	def save(self, user, commit=True):
		justificativa = super(EditJustificativaForm, self).save(commit=False)
		setor = justificativa.vinculo.setor
		vinculos = user.vinculos.filter(ativo=True)
		vinculos = user.vinculos.filter(Q(setor=setor) | Q(coordenadoria=setor.coordenadoria))

		if vinculos:
			justificativa.usuario_analise = vinculos.first()
		else:
			raise forms.ValidationError("Usuário não autorizado para homologar justificativa de falta")

		if commit:
			justificativa.save()

		return justificativa

frequencia/justificativas/views.py
from rules.contrib.views import PermissionRequiredMixin, permission_required, objectgetter

from django.db.models import Q
from django.urls import reverse
from django.contrib import messages
from django.views.generic import ListView
from django.http import HttpResponseRedirect
from django.views.generic.detail import DetailView
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, get_object_or_404, redirect

from frequencia.vinculos.models import Coordenadoria, Setor
from frequencia.vinculos.utils import get_setores

from .models import TipoJustificativaFalta, JustificativaFalta
from .forms import EditTipoJustificativaForm, CreateJustificativaForm, EditJustificativaForm

#Tipos de justificativa
class TipoJustificativaListView(PermissionRequiredMixin, ListView):

	model = TipoJustificativaFalta
	template_name = 'tipo_justificativa/tipo_justificativa.html'
	permission_required = 'tipo_justificativa.can_manage'


class TipoJustificativaCreateView(PermissionRequiredMixin, SuccessMessageMixin, CreateView):

	model = TipoJustificativaFalta
	form_class = EditTipoJustificativaForm
	template_name = 'tipo_justificativa/tipo_justificativa_create_edit.html'
	permission_required = 'tipo_justificativa.can_manage'

	success_message = 'Tipo de justificativa cadastrado com sucesso!'

	def get_success_url(self):
		return reverse('justificativas:tipo_justificativa')


class TipoJustificativaUpdateView(PermissionRequiredMixin, SuccessMessageMixin, UpdateView):

	model = TipoJustificativaFalta
	form_class = EditTipoJustificativaForm
	template_name = 'tipo_justificativa/tipo_justificativa_create_edit.html'
	permission_required = 'tipo_justificativa.can_manage'

	success_message = 'Tipo de justificativa atualizado com sucesso!'

	def get_success_url(self):
		return reverse('justificativas:tipo_justificativa')


@permission_required('tipo_justificativa.can_manage')
def tipo_justificativa_remove(request, pk):

	tipo_justificativa = get_object_or_404(TipoJustificativaFalta, pk=pk)
	tipo_justificativa.delete()
	messages.success(request, 'Tipo de justificativa de falta excluído com sucesso!')
	return redirect('justificativas:tipo_justificativa')


#Justificativa de falta
class JustificativaListView(LoginRequiredMixin, ListView):

	model = JustificativaFalta
	template_name = 'justificativas/justificativas.html'

	def get_queryset(self, **kwargs):		

		user = self.request.user

		busca = self.request.GET.get('busca', '')
		justificativas = JustificativaFalta.objects.buscar(busca).order_by('vinculo__setor__pk')

		if not busca:
			justificativas = justificativas.filter(status=0)

		if user.has_perm('accounts.is_gestor'):
			return justificativas.all()			

		if user.has_perm('accounts.is_coordenador_chefe'):
			setores = get_setores(user)
			return justificativas.filter(vinculo__setor__in=setores)
		
		return justificativas.filter(vinculo__user=user)

class JustificativaCreateView(PermissionRequiredMixin, SuccessMessageMixin, CreateView):

	model = JustificativaFalta
	form_class = CreateJustificativaForm
	template_name = 'justificativas/justificativa_create.html'
	permission_required = 'justificativa.can_create'

	success_message = 'Justificativa de falta cadastrada com sucesso!'

	def form_valid(self, form):
		form.save(self.request.user)
		messages.info(self.request, self.success_message)		
		return HttpResponseRedirect(self.get_success_url())

	def get_success_url(self):
		return reverse('justificativas:justificativas')


class JustificativaUpdateView(PermissionRequiredMixin, SuccessMessageMixin, UpdateView):

	model = JustificativaFalta
	form_class = EditJustificativaForm
	template_name = 'justificativas/justificativa_detail.html'
	permission_required = 'justificativa.can_view'

	success_message = 'Justificativa de falta homologada com sucesso'

	def form_valid(self, form):
		user = self.request.user
		if user.has_perm('justificativa.can_analyse', self.object):
			form.save(self.request.user)
			messages.info(self.request, self.success_message)
			return HttpResponseRedirect(self.get_success_url())
		else:
			raise PermissionDenied()

	def get_success_url(self):
		return reverse('justificativas:justificativa_edit', kwargs={'pk' : self.object.pk})

	def get_context_data(self, **kwargs):
		context = super(JustificativaUpdateView, self).get_context_data(**kwargs)
		context['numero_dias_falta'] = abs((self.object.inicio - self.object.termino).days) + 1
		return context

@permission_required('justificativa.can_reabrir', fn=objectgetter(JustificativaFalta, 'pk'))
def justificativa_reabrir(request, pk):
	justificativa = get_object_or_404(JustificativaFalta, pk=pk)

	justificativa.status = 0
	justificativa.usuario_analise = None
	justificativa.horas_abonadas = None
	justificativa.save()

	messages.info(request, 'Justificativa reaberta com sucesso')
	return redirect('justificativas:justificativa_edit', pk=pk)

@permission_required('justificativa.can_delete', fn=objectgetter(JustificativaFalta, 'pk'))
def justificativa_excluir(request, pk):
	justificativa = get_object_or_404(JustificativaFalta, pk=pk)		
	justificativa.delete()

	messages.info(request, 'Justificativa removida com sucesso')
	return redirect('justificativas:justificativas')


#Tipos de justificativa
tipo_justificativa = TipoJustificativaListView.as_view()
tipo_justificativa_create = TipoJustificativaCreateView.as_view()
tipo_justificativa_edit = TipoJustificativaUpdateView.as_view()

#Justificativa de falta
justificativas = JustificativaListView.as_view()
justificativa_create = JustificativaCreateView.as_view()
justificativa_edit = JustificativaUpdateView.as_view()

frequencia/justificativas/templates/justificativas/justificativa_detail.html
{% extends 'base.html' %}
{% load static %}
{% load filtros %}

{% load rules %}


{% block content %}

    {% load widget_tweaks %}
    {% load timedelta_filter %}
    {% has_perm 'justificativa.can_analyse' user object as can_analyse %}
    {% has_perm 'accounts.is_gestor' user object as is_gestor %}
    {% has_perm 'justificativa.justificativa_author' user object as justificativa_author %}

<div class="card mb-3">
    <div class="card-header">
      <i class="far fa-comment"></i> Justificativa de falta
    </div>
    <div class="card-body">     
        <div class="row">
            
            <div class="form-group col-md-6">
                <label>Período</label>
                <p class="font-weight-bold">{{object.inicio|date:"d/m/Y"}} a {{object.termino|date:"d/m/Y"}} ({{numero_dias_falta}} dia{{numero_dias_falta|pluralize}})</p>
            </div>

            <div class="form-group col-md-6">
                <label>Tipo</label>
                <p class="font-weight-bold">{{ object.tipo }}</p>
            </div>
        
            <div class="col-md-6">
                <div class="form-group">
                    <label>Bolsista</label>
                    <input type="text" class="form-control" value="{{object.vinculo.user}}" readonly="readonly">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>Setor</label>
                    <input type="text" class="form-control" value="{{object.vinculo.setor}}" readonly="readonly">
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label>Status</label>
                    <input type="text" class="form-control" value="{{object.get_status_display}}" readonly="readonly">
                </div>
            </div>
        
            <div class="col-md-12 text-justify">
                <div class="form-group">
                    <label>Descrição:</label>
                    <p>{{object.descricao}}</p>
                </div>
            </div>

            <div class="form-group col-md-12">
                {% if object.comprovante %}
                    <a href="{{ object.comprovante.url }}" target="_blank">
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-paperclip fa-stack-1x"></i>                        
                    </span>
                    {{ object.comprovante|filename }}</a>
                {% else %}
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-paperclip fa-stack-1x"></i>
                        <i class="fa fa-ban fa-stack-2x text-danger"></i>
                    </span>
                    <label>Nenhum comprovante</label>
                {% endif %} 
            </div>     
        </div>
       
        <hr>
        <h5>Análise da justificativa de falta</h5>
        {% if not object.usuario_analise %}
            {% if can_analyse %}                        
                <div class="content">
                    <form action="#" method="post">
                         {% csrf_token %}
                         {% if form.non_field_errors %}
                            <div class="alert alert-danger">
                                {% for error in form.non_field_errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label>{{ form.status.label }}</label>
                                {% render_field form.status class="form-control" %}
                                {% if form.status.errors %}
                                    <label class="text-danger">{{ form.status.errors.0 }}</label>
                                {% endif %}
                            </div>
                            <div class="form-group col-md-6">
                                <label>{{ form.horas_abonadas.label }}</label>
                                {% render_field form.horas_abonadas class="form-control" %}
                                {% if form.horas_abonadas.errors %}
                                    <label class="text-danger">{{ form.horas_abonadas.errors.0 }}</label>
                                {% endif %}
                            </div>
                            <div class="form-group col-md-12">
                                <label>{{ form.parecer.label }}</label>
                                {% render_field form.parecer class="form-control" %}
                                {% if form.parecer.errors %}
                                    <label class="text-danger">{{ form.parecer.errors.0 }}</label>
                                {% endif %}
                            </div>
                        </div>
                        <div class="text-center">
                            <a class="btn text-info" href="{% url 'justificativas:justificativas' %}">Voltar</a>
                            <button class="btn btn-info confirm-modal" data-toggle="modal" data-target="#confirmar_homologacao" type="button">Salvar</button>
                        </div>

                        <!-- Modal de confirmação -->
                        <div class="modal fade" id="confirmar_homologacao" tabindex="-1" role="dialog" style="display: none;">
                          <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <div class="modal-header">                                
                                <h4 class="modal-title" id="myModalLabel">Avaliação de justificativa de falta</h4>
                              </div>
                              <div class="modal-body">
                                Você deseja realmente homologar a justificativa? Esta operação não pode ser desfeita.
                                <br><br>
                                <b>Bolsista:</b> {{object.vinculo.user}}<br>
                                <b>Setor:</b> {{object.vinculo.setor}}<br>
                                <b>Período:</b> {{object.inicio|date:"d/m/Y"}} à {{object.termino|date:"d/m/Y"}} <b class="text-danger">({{numero_dias_falta}} dia{{numero_dias_falta|pluralize}})</b><br><br>
                                Horas abonadas: <h5 class="text-danger" id="horas_abonadas_modal"></h5><br>
                                <input type="checkbox" id="confirma_leitura"> Confirmo estar de acordo com as informações acima
                              </div>
                              <div class="modal-footer">
                                <a href="#" class="btn text-info" data-dismiss="modal">Cancelar</a>
                                <button type="submit" id="botao_confirmar" class="btn btn-danger" disabled>Confirmar</button>
                              </div>
                            </div>
                          </div>
                        </div>
                        <!-- Fim do modal-->
                    </form>                            
                </div>                        
            {% else %}
                <div class="content">
                    <div class="alert alert-warning">
                        <span>Aguardando análise da chefia</span>
                    </div>
                </div>
                {% if justificativa_author %}
                    <div class="text-center">
                        <a href="#" class="btn btn-danger" data-toggle="modal" data-target="#confirmar_exclusao">Cancelar justificativa</a>
                    </div>

                    <div class="modal fade" id="confirmar_exclusao" tabindex="-1" role="dialog" style="display: none;">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">                                
                            <h4 class="modal-title" id="myModalLabel">Cancelamento de justificativa</h4>
                          </div>
                          <div class="modal-body">
                            Você deseja realmente cancelar a justificativa de falta? Esta operação é irreversível.
                          </div>
                          <div class="modal-footer">
                            <a href="#" class="btn text-info" data-dismiss="modal">Fechar</a>
                            <a href="{% url 'justificativas:justificativa_excluir' object.pk %}" class="btn btn-danger">Confirmar</a>
                          </div>
                        </div>
                      </div>
                    </div>
                {% endif %}
            {%endif%}
        {% else %}                    
            <div class="content">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Avaliado por</label>
                            <input type="text" class="form-control" value="{{ object.usuario_analise.user.name }}" readonly="readonly">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Horas abonadas</label>
                            <input type="text" class="form-control" value="{{ object.horas_abonadas }}" readonly="readonly">
                        </div>
                    </div>
                {% if object.parecer %}                    
                    <div class="col-md-8 text-justify">
                        <div class="form-group">
                            <label>Parecer da chefia:</label>
                            <p>{{object.parecer}}</p>
                        </div>
                    </div>
                {% endif %}  
                </div>  

                <div class="text-center">
                    <a href="#" class="btn text-info" onclick="window.history.back()">Voltar</a>
                    {% if is_gestor %}
                        <button class="btn btn-danger" data-toggle="modal" data-target="#confirmar_reabertura">Reabrir justificativa</button>                        
                    {% endif %}
                </div>

                {% if is_gestor %}
                <div class="modal fade" id="confirmar_reabertura" tabindex="-1" role="dialog" style="display: none;">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">                                
                        <h4 class="modal-title" id="myModalLabel">Reabertura de justificativa de falta</h4>
                      </div>
                      <div class="modal-body">
                        Você deseja realmente reabrir a justificativa de falta? A justificativa deverá ser reavaliada pela chefia do bolsista.
                      </div>
                      <div class="modal-footer">
                        <a href="#" class="btn text-info" data-dismiss="modal">Cancelar</a>
                        <a href="{% url 'justificativas:justificativa_reabrir' object.pk %}" class="btn btn-danger">Confirmar</a>
                      </div>
                    </div>
                  </div>
                </div>
                {% endif %}
            </div>
        {%endif%}
    </div>    
</div>

{% endblock %}

{% block extra-scripts %}
    <script src="{% static 'js/jquery.mask.js' %}"></script>

    {% has_perm 'justificativa.can_analyse' user object as can_analyse %}

    {% if can_analyse and not object.usuario_analise %}
        <script type="text/javascript">
          $(document).ready(function(){
             $('#id_horas_abonadas').mask('00:00:00', {reverse: true});

             $('#id_horas_abonadas').val('{{object.horas_sugeridas|timedelta:"{hours_total}:{minutes2}:{seconds2}"}}');

             $('.confirm-modal').on('click', function(){
                var _horas = $('#id_horas_abonadas').val();
                $("#horas_abonadas_modal").text(_horas);
             });

             $("#confirma_leitura").change(function(){
                if(this.checked){
                    $('#botao_confirmar').attr("disabled", false);                
                } else {
                    $('#botao_confirmar').attr("disabled", true);  
                }
             });
          });
        </script>
    {% endif %}
{% endblock %}

frequencia/justificativas/templates/justificativas/justificativa_mail.html
<h3>Uma nova justificativa de falta foi cadastrada</h3>
<br>
<p><strong>Bolsista:</strong> {{ justificativa.vinculo.user }} </p>
<p><strong>Setor:</strong> {{ justificativa.vinculo.setor }} </p>
<p><strong>Período:</strong> {{ justificativa.inicio }} a {{ justificativa.termino }}</p>

<p><strong>Descrição da justificativa:</strong> {{ justificativa.descricao|linebreaks }}</p>

<p>Para visualizar o item, acesse: {{ base_url }}{% url 'justificativas:justificativa_edit' justificativa.pk %}</p>
<br><br><br>
<p align="center">
	Sistema de Gerenciamento de Frequência de Bolsistas<br>
	Biblioteca Central Zila Mamede
</p>